### ISSUE TITLE
Rename package to 'zenodo-get' to match pypi?

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/zenodo_get-feedstock#1]
Is it possible/reasonable to rename this conda package `zenodo-get` to match the PyPI package name?

**Comment by ickc** [comment]
Even the doc at https://gitlab.com/dvolgyes/zenodo_get asked the user to `pip3 install zenodo_get`. I think it is better to ask the upstream to decide which one they want to stick to first and be internally consistent.

I'm not sure how to rename a conda-forge feedstock, and may be the easiest way is just to create a new feedstock and discontinue this one if we really want to rename.

**Comment by duncanmmacleod** [comment]
I think this might be a PyPI quirk that the package is properly called `zenodo_get` but PyPI allows and encourages the use of `zenodo-get`? Either way this is an upstream issue. Thanks.
